# Generated by Django 5.0.4 on 2024-05-15 11:39

from django.db import migrations
from Events.models import CustomUser, Status

def add_base_interests(apps, schema_editor):
    Interests = apps.get_model("Events", "Interests")

    list_of_interes = ["Музыка", 'Искусство', "Спорт", "Образование",
                       "Гастрономия", "Развлечения", "Здоровье", "Наука"]
    for i in list_of_interes:
        Interests.objects.create(interest=i)


def add_default_super_user(apps, schema_editor):
    superuser = CustomUser.objects.create_superuser(
        username='admin',
        email='admin@example.com',
        password='admin',
        is_staff=True,
        is_superuser=True,
        status = Status.objects.filter(status="admin").first(),
    )

    superuser.save()

def add_default_user_status(apps, schema_editor):
    statuses = apps.get_model("Events", "Status")

    list_of_statuses = ["admin", "expert"]
    for i in list_of_statuses:
        statuses.objects.create(status=i)


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_base_interests),
        migrations.RunPython(add_default_user_status),
        migrations.RunPython(add_default_super_user),
    ]
